language: cpp
sudo: required
#dist: trusty


# sdl2
before_install:
- sudo add-apt-repository -y ppa:team-xbmc/ppa
- sudo apt-get update -qq
- sudo apt-get install -y clang-5.0 libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

# safelist
branches:
  only:
  - master
  - stable


os:
- linux

# compilers to test against
compiler: clang++

script: 
- if [ $TRAVIS_OS_NAME == linux ]; then 
- mkdir build
- cd build 
- cmake .. 
- CC=clang-5.0 CXX=clang++-5.0 CXXFLAGS=-std=c++14 make -j8
- fi
