language: cpp
sudo: required
#dist: trusty

# sdl2
before_install:
- sudo add-apt-repository -y ppa:team-xbmc/ppa
- sudo apt-get update -qq
- sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

# safelist
branches:
  only:
  - master
  - stable


os:
- linux

# compilers to test against
compiler: clang

script: if [ $TRAVIS_OS_NAME == linux ]; then mkdir build && cmake .. && make; fi
